name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore "Src/Newtonsoft.Json.sln"
    - name: Build
      run: dotnet build --no-restore -p:TargetFrameworks="netstandard1.0;netstandard1.3;netstandard2.0" "Src/Newtonsoft.Json.sln"
    - name: Test
      run: dotnet test --no-build -p:TargetFrameworks="netstandard1.0;netstandard1.3;netstandard2.0" --verbosity normal "Src/Newtonsoft.Json.sln"
