name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  SOLUTION: "Src/Newtonsoft.Json.sln"
  NUNIT_VERSION: 3.8.0

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore ${{ env.SOLUTION }}

    - name: Build
      run: msbuild /p:Configuration=Release ${{ env.SOLUTION }}

    - name: Test
      run: dotnet test Src\Newtonsoft.Json.sln -c Release -l trx --no-restore --no-build

    - name: Restore NUnit
      run: nuget install NUnit.ConsoleRunner -Version ${{ env.NUNIT_VERSION }} -ConfigFile "Src\nuget.config"

#    -name: Run NUnit tests
#      run: nunit3-console.exe "$testRunDir\Newtonsoft.Json.Tests.dll" --framework=$framework --result=$workingDir\$testDir.xml --out=$workingDir\$testDir.txt | Out-Default } "Error running $testDir tests"